### ISSUE TITLE
Disable non-code syntax match in literate haskell

### ISSUE THREAD

**Issue by dandoh** [carymrobbins/intellij-haskforce#388] opened 2019-05-05 18:49 UTC
In the document section of literate haskell file, it looks like this:
![image](https://user-images.githubusercontent.com/10379980/57198769-c67c3980-6f44-11e9-8367-ca2f076a1690.png)
I don't know if this is a real issue, but what can I do if I don't want those non-code words being colored?

**Comment by carymrobbins** [comment] 2019-05-05 19:10
Right now `*.lhs` files are associated with Haskell, but we don't have any special handling in the lexer/parser for this. See #356.

I see that there's a [LaTeX plugin](https://plugins.jetbrains.com/plugin/7660-latex). I haven't used it, but I wonder if it might help with this, allowing for _language injection_ in the code blocks.

Alternatively, you could disable syntax highlighting altogether by going to `Preferences > Editor > File Types > Haskell` and removing `*.lhs`, but that might be worse for you.

**Comment by carymrobbins** [comment] 2019-05-05 19:11
Closing as this is a duplicate of #356. If you'd like, let's continue the discussion there.

**Closed by carymrobbins** 2019-05-05 19:11 UTC

**Comment by dandoh** [comment] 2019-05-05 19:58
Thank you for your help. I found a solution for this:
Using Textmate Bundle plugin:
- https://www.jetbrains.com/help/idea/tutorial-using-textmate-bundles.html
And Haskell bundle:
- https://github.com/textmate/haskell.tmbundle
Now I get something like this, which is pretty good:
![image](https://user-images.githubusercontent.com/10379980/57199570-a2bdf100-6f4e-11e9-8978-e618ce85aa51.png)
