### ISSUE TITLE
Can't create project

### ISSUE THREAD

**Issue by orome** [carymrobbins/intellij-haskforce#184] opened 2015-08-27 19:50 UTC
I get as far as the final step of project creation and the process hangs (attempting to click the finish) button has no effect. 

If I go back and don't create a cabal file, I can then proceed, but end up with a project I can't build.

**Comment by carymrobbins** [comment] 2015-08-27 21:54
What OS are you using?  What is the cabal path set to?  If you create a project without a Cabal file, try to go to **Tools > Add Cabal Package** and try to create it that way, except use `.` for the **Root Directory**.  See if that works for you.

Either way, some sort of error should be reported to you for this.  Could you provide some screen shots of what info is filled out in the **New Project** forms?

**Comment by orome** [comment] 2015-08-29 11:07
I choose New Project, Next, Next, Next, Next, Finish; and nothing happens. If I go back and uncheck Cabal generation, I can proceed, but then I can't build anything. If I go back and generate manually as suggested I get

    Add Cabal Package
    cabal:
    '/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/bin/ghc'
    exited with an error:
    ghc: missing -B option (show balloon)
    Add Cabal Package: Could not find new cabal file at /Users/Rax/Documents/Projects/Coding/untitled3/untitled3.cabal - may not have been created.

GHC Path: `/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/bin/ghc`
Cabal: `/usr/bin/cabal`

IntelliJ IDEA 14.1.4; OS X: 10.10.5; Xcode: 6.4; CLT: 6.4.0.0.1; Clang: 6.1; Homebrew Python (2.7.10_2); Java: 1.6.0_65

**Comment by orome** [comment] 2015-09-12 13:15
Any news on this? Are there other Haskell plugins that are recommended and active that I might use instead?

**Comment by carymrobbins** [comment] 2015-09-12 13:38
Sorry for the delay, I haven't been able to reproduce yet.

One thing you might want to try is `cd`ing into your project directory and running `cabal init` (which is what is used under the hood).  This may give some clues as to what's happening.

**Comment by orome** [comment] 2015-09-12 13:43
Should I run that after the plugin fails there, or just in a new directory where I plan to put the project?

**Comment by carymrobbins** [comment] 2015-09-12 13:46
I would try it in the directory for the project where it already failed.

**Comment by orome** [comment] 2015-09-12 14:36
If I do that, `cabal init` works, as does `cabal build` (generating an executable I can run in `./dist/build/ProjName`. (FIIW, I'm new to both Haskell and esp. Cabal, so it's not clear to me what Cabal is doing.)

**Comment by carymrobbins** [comment] 2015-09-12 15:10
Ok, good to know.  I'm guessing if you do `which cabal` and `which ghc` you get the same paths as listed above?

I'll work on this and try to get the fix out ASAP.  Also, I released an update a few days ago, so you may want to upgrade HaskForce to ensure the bug remains in the new version.

**Comment by orome** [comment] 2015-09-12 15:22
Ah, no: `which -a ghc` gives `/usr/bin/ghc` (which points at ` /Library/Haskell/ghc-7.10.2-x86_64/bin/cabal`). If I enter `/usr/bin/ghc`, things do seem to work (at least something is generated, though I get warnings about a missing license file and am not sure how the create a suitable run config).

**Comment by carymrobbins** [comment] 2015-09-13 02:43
It sounds like you are running into a buffering issue.  Here's one way you can fix the problem -

```haskell
module Main where

import System.IO

main = do
  hSetBuffering stdout NoBuffering
  putStrLn "x:"
  x <- readLn
  putStrLn "y:"
  y <- readLn
  putStrLn $ "x + y = " ++ show (x + y)
```

**Comment by orome** [comment] 2015-09-13 12:14
Cool. That does the trick. Why do I need that in the IDE and not at the command line?

**Comment by orome** [comment] 2015-09-13 12:20
(Will this work in *PyCharm*, btw?)

**Comment by carymrobbins** [comment] 2015-09-14 03:42
I'm not exactly sure why that buffering issue occurs.  It might have something to do with OSProcessHandle, used in [HaskellApplicationCommandLineState](https://github.com/carymrobbins/intellij-haskforce/blob/master/src/com/haskforce/run/HaskellApplicationCommandLineState.java).

Regarding PyCharm integration, there's an open ticket for it (#65).  It's a bigger change, but I am in the middle of improving the build system and integrating stack, so I may be able to get it working.  I discuss the problems and possible approach in that ticket.

**Comment by orome** [comment] 2015-09-16 12:42
To clarify, the bug here turns out not to be that I can't create a project (I can if I have the GHC path that `which ghc` reports) but that no matter what I do, the proposed path lists

    /Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/bin/ghc

as the path, which cause the blocking described above.

If I manually enter `/usr/bin/ghc`then everything works.

Note that `/usr/bin/ghc` points to

    /Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/bin/ghc

which points in turn to `ghc-7.10.2`. I'm not sure why HaskForce keeps coming up with the other path above.

**Comment by orome** [comment] 2015-09-16 15:24
And, FWIW, heres what's in that directory:
```
> ls -lFAG /Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/bin

lrwxr-xr-x  1 root  wheel     10 Aug 14 11:29 ghc@ -> ghc-7.10.2
-rwxr-xr-x  1 root  wheel    464 Aug  2 22:15 ghc-7.10.2*
lrwxr-xr-x  1 root  wheel     14 Aug 14 11:29 ghc-pkg@ -> ghc-pkg-7.10.2
-rwxr-xr-x  1 root  wheel    496 Aug  2 22:15 ghc-pkg-7.10.2*
lrwxr-xr-x  1 root  wheel     11 Aug 14 11:29 ghci@ -> ghci-7.10.2
-rwxr-xr-x  1 root  wheel    112 Aug  2 22:15 ghci-7.10.2*
lrwxr-xr-x  1 root  wheel     18 Aug 14 11:29 haddock@ -> haddock-ghc-7.10.2
-rwxr-xr-x  1 root  wheel    455 Aug  2 22:15 haddock-ghc-7.10.2*
-rwxr-xr-x  1 root  wheel  43768 Aug  2 22:15 hp2ps*
-rwxr-xr-x  1 root  wheel    426 Aug  2 22:15 hpc*
-rwxr-xr-x  1 root  wheel   1230 Aug  2 22:15 hsc2hs*
lrwxr-xr-x  1 root  wheel     13 Aug 14 11:29 runghc@ -> runghc-7.10.2
-rwxr-xr-x  1 root  wheel    447 Aug  2 22:15 runghc-7.10.2*
lrwxr-xr-x  1 root  wheel      6 Aug 14 11:29 runhaskell@ -> runghc
```

**Comment by carymrobbins** [comment] 2015-09-16 22:22
Is `/Library/Frameworks/GHC.framework/Versions/7.10.2-x86_64/usr/lib/ghc-7.10.2/bin/ghc` a valid path to GHC?

**Comment by orome** [comment] 2015-09-17 15:53
Yes.

**Comment by carymrobbins** [comment] 2015-09-17 16:07
Ok, so HaskForce is finding it in your PATH and suggesting it by default.  You can change the default just like you would for the [external tools](https://github.com/carymrobbins/intellij-haskforce/wiki/Quick-Start-Guide#configuring-external-tools) by going to -

**File > Other Settings > Default Settings > Build > Compiler > Haskell Compiler**

Just set the GHC you want it to use by default and moving forward the IDE will suggest it by default.

**Comment by juliaMarin** [comment] 2015-09-25 10:45
Hi, I have the same problem but in Ubuntu 14.04. I thought to add it here because is the same problem but different OS. Just download haskforce today so it should have the latest code.

**Comment by juliaMarin** [comment] 2015-09-25 11:02
I'm sorry, I've installed haskell-platform:
sudo apt-get install haskell-platform
Which has the cabal version 1.16.0.2 

Just updating to the right one =< 1.18 fixed.

Thanks and sorry.

**Comment by carymrobbins** [comment] 2015-10-10 00:02
**Required Solution** - Report errors to the user after calling `cabal init` from the new project wizard.  If it fails, we should still create the project, just warn the user once it opens so it can be corrected at that time.

**Comment by carymrobbins** [comment] 2015-11-20 06:16
@orome - Closing as this should be resolved in the latest release.  We no longer call `cabal init` from the project wizard.

**Closed by carymrobbins** 2015-11-20 06:16 UTC
Labels: bug
